server {
    listen 8080;

    # Serve the React build
    location / {
        root /usr/share/nginx/html;
        try_files $uri $uri/ /index.html;
    }

    # Proxy API calls to the backend service
    location /api/ {
        proxy_pass http://populi-backend-svc:5000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
