apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: populi

resources:
  - ../../base

# Image tags are updated automatically by GitHub Actions on each push to main
images:
  - name: ghcr.io/yoramvandevelde/populi-frontend
    newTag: 08e016c3 # frontend
  - name: ghcr.io/yoramvandevelde/populi-backend
    newTag: 08e016c3 # backend
